import React from "react";
import { uid } from 'uid';

export const productList = [
  {
      id: uid(),
      productName: "Chaldal Sippy Orange Drinks",
      category: "Food",
      subCategory: "Beverages",
      subsubCategory: "Syrups & Powder Drinks",
      subsubcategoryImage: "https://chaldn.com/_mpimage/syrups-powder-drinks?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D30220&q=best&v=1&m=400&webp=1",
      subCategoryImage: "https://chaldn.com/_mpimage/beverages?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D23727&q=low&v=1&m=400&webp=1",
      productImage: "https://chaldn.com/_mpimage/chaldal-sippy-orange-drinks-500-gm?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D154114&q=best&v=1&m=400&webp=1",
      addedInCart: 0,
      stock: 100,
      unitPrice: 500,
      discount: 40,
      weight: "500 gm",
      popular: true,
      offer: false,
      offerImage: null,
      favorite: false,
      ramadan: true,
      offerImage: "https://chaldn.com/_mpimage?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D154570&q=low&v=1&m=400&webp=1"
  },
  {
      id: uid(),
      productName: "Chaldal Sippy Mango Drinks",
      category: "Food",
      subCategory: "Beverages",
      subsubCategory: "Syrups & Powder Drinks",
      subsubcategoryImage: "https://chaldn.com/_mpimage/syrups-powder-drinks?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D30220&q=best&v=1&m=400&webp=1",
      subCategoryImage: "https://chaldn.com/_mpimage/beverages?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D23727&q=low&v=1&m=400&webp=1",
      productImage: "https://chaldn.com/_mpimage/chaldal-sippy-mango-drinks-500-gm?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D154116&q=best&v=1&m=400&webp=1",
      addedInCart: 0,
      stock: 100,
      unitPrice: 500,
      discount: 40,
      weight: "500 gm",
      popular: true,
      offer: false,
      offerImage: null,
      favorite: false,
      ramadan: true,
      offerImage: "https://chaldn.com/_mpimage?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D154570&q=low&v=1&m=400&webp=1"
  },
  {
      id: uid(),
      productName: "Dettol Soap Bathing Bar Original Germ Defence 75 gm (Free Tiffin Box)",
      category: "Cleaning Supplies",
      subCategory: "Dishwashing Supplies",
      subsubCategory: null,
      subsubcategoryImage: null,
      subCategoryImage: "https://chaldal.com/dish-wash",
      productImage: "https://chaldn.com/_mpimage/dettol-soap-bathing-bar-original-germ-defence-75-gm-free-tiffin-box-3-pcs?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D151122&q=best&v=1&m=400&webp=1",
      addedInCart: 0,
      stock: 100,
      unitPrice: 180,
      discount: 12,
      weight: "3 pcs",
      popular: true,
      offer: true,
      favorite: false,
      ramadan: false,
      offerImage: "https://chaldn.com/_mpimage?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D149095&q=low&v=1&m=400&webp=1"
  },
  {
      id: uid(),
      productName: "Crown Dabbas Dates",
      category: "Food",
      subCategory: "Fruits & Vegetables",
      subsubCategory: "Fresh Fruits",
      subsubcategoryImage: "https://chaldn.com/_mpimage/syrups-powder-drinks?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D30220&q=best&v=1&m=400&webp=1",
      subCategoryImage: "https://chaldal.com/fruits-vegetables",
      productImage: "https://chaldn.com/_mpimage/crown-dabbas-dates-1-kg?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D129412&q=best&v=1&m=400&webp=1",
      addedInCart: 0,
      stock: 100,
      unitPrice: 650,
      discount: 16,
      weight: "500 gm",
      popular: true,
      offer: false,
      favorite: false,
      ramadan: true,
      offerImage: null,
  },
  {
      id: uid(),
      productName: "Crown Dabbas Dates",
      category: "Food",
      subCategory: "Fruits & Vegetables",
      subsubCategory: "Fresh Fruits",
      subsubcategoryImage: "https://chaldn.com/_mpimage/syrups-powder-drinks?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D30220&q=best&v=1&m=400&webp=1",
      subCategoryImage: "https://chaldal.com/fruits-vegetables",
      productImage: "https://chaldn.com/_mpimage/chaldal-sippy-orange-drinks-500-gm-and-crown-dabbas-dates-1-kg-combo-offer?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D154429&q=best&v=1&m=400&webp=1",
      addedInCart: 0,
      stock: 100,
      unitPrice: 1150,
      discount: 33,
      weight: "500 gm",
      popular: true,
      offer: false,
      favorite: false,
      ramadan: true,
      offerImage: null,
  },
  {
      id: uid(),
      productName: "Crown Dabbas Dates",
      category: "Food",
      subCategory: "Fruits & Vegetables",
      subsubCategory: "Fresh Fruits",
      subsubcategoryImage: "https://chaldn.com/_mpimage/syrups-powder-drinks?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D30220&q=best&v=1&m=400&webp=1",
      subCategoryImage: "https://chaldal.com/fruits-vegetables",
      productImage: "https://chaldn.com/_mpimage/crown-dabbas-dates-1-kg?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D129412&q=best&v=1&m=400&webp=1",
      addedInCart: 0,
      stock: 100,
      unitPrice: 650,
      discount: 16,
      weight: "500 gm",
      popular: true,
      offer: false,
      favorite: false,
      ramadan: true,
      offerImage: null,
  },
  {
      id: uid(),
      productName: "Date Crown Lulu Dates",
      category: "Food",
      subCategory: "Fruits & Vegetables",
      subsubCategory: "Fresh Fruits",
      subsubcategoryImage: "https://chaldn.com/_mpimage/syrups-powder-drinks?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D30220&q=best&v=1&m=400&webp=1",
      subCategoryImage: "https://chaldal.com/fruits-vegetables",
      productImage: "https://chaldn.com/_mpimage/date-crown-lulu-dates-400-gm?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D129300&q=best&v=1&m=400&webp=1",
      addedInCart: 0,
      stock: 100,
      unitPrice: 350,
      discount: 10,
      weight: "400 gm",
      popular: true,
      offer: false,
      favorite: false,
      ramadan: true,
      offerImage: null,
  },
]
export const categories = [
  {
    name: "Favourites",
    subCategories: null,
    path: "/favourites",
  },
  {
    name: "Ramadan",
    subCategories: null,
    path: "/ramadan",
  },
  {
    name: "Flash Sales",
    subCategories: null,
    path: "/flash-sales",
  },
  {
    name: "Popular",
    subCategories: null,
    path: "/popular",
  },
  {
    name: "Food",
    subCategories: [
      {
        name: "Fruits & Vegetables",
        subCategories: [
          {
            name: "Fresh Vegetables",
            subCategories: null,
            path: "/food/fruits-and-vegetables/fresh-vegetables",
          },
          {
            name: "Fresh Fruits",
            subCategories: null,
            path: "/food/fruits-and-vegetables/fresh-fruits",
          },
          {
            name: "Dates (Khejur)",
            subCategories: null,
            path: "/food/fruits-and-vegetables/dates",
          },
        ],
        path: "/food/fruits-and-vegetables",
      },
      {
        name: "Meat & Fish",
        subCategories: [
          {
            name: "Chicken & Poultry",
            subCategories: null,
            path: "/food/meat-and-fish/chicken-and-poultry",
          },
          {
            name: "Premium Perishables",
            subCategories: null,
            path: "/food/meat-and-fish/premium-perishables",
          },
          {
            name: "Frozen Fish",
            subCategories: null,
            path: "/food/meat-and-fish/frozen-fish",
          },
          {
            name: "Meat",
            subCategories: null,
            path: "/food/meaf-and-fish/meat",
          },
          {
            name: "Tofu & Meat Alternatives",
            subCategories: null,
            path: "/food/meaf-and-fish/tofu-and-meat-alternatives",
          },
          {
            name: "Dried Fish",
            subCategories: null,
            path: "/food/meat-and-fish/dried-fish",
          },
        ],
        path: "/food/meat-and-fish",
      },
      {
        name: "Cooking",
        subCategories: [
          {
            name: "Spices",
            subCategories: null,
            path: "/food/cooking/spices",
          },
          {
            name: "Salt & Sugar",
            subCategories: null,
            path: "/food/cooking/salt-and-sugar",
          },
          {
            name: "Rice",
            subCategories: null,
            path: "/food/cooking/rice",
          },
          {
            name: "Dal or Lentil",
            subCategories: null,
            path: "/food/cooking/dal-or-lentil",
          },
          {
            name: "Ready Mix",
            subCategories: null,
            path: "/food/cooking/read-mix",
          },
          {
            name: "Shemai & Suji",
            subCategories: null,
            path: "/food/cooking/shemai-and-suji",
          },
          {
            name: "Oil",
            subCategories: null,
            path: "/food/cooking/oil"
          },
          {
            name: "Colors & Flavours",
            subCategories: null,
            path: "/food/cooking/colors-and-flavours"
          },
          {
            name: "Ghee",
            subCategories: null,
            path: "/food/cooking/ghee"
          },
          {
            name: "Premium Ingredients",
            subCategories: null,
            path: "/food/cooking/premium-ingredients"
          },
        ],
        path: "/food/cooking",
      },
    ],
    path: "/food"
  },
];
